### PR TITLE
Standard Library

### LINKED ISSUE #122: Support `size` member variable for arrays

### LINKED ISSUE #258: Attempting to access property of array crashes compiler
An error should be produced instead.

### PR DESCRIPTION
**Pull request by DJRHails**
Fixes #122 
Fixes #258 

# Implementation Overview
The standard library is expanded in scope in this PR.

Runtime functions are removed from explicit hardcoding in the compiler, and instead defined in the standard library under runtimes.

This has also lead to reworking structs to support static functions when they don't have any properties or initialisers - may make sense to support static functions explicitly.

# Future
Standard types should also being defined in the standard library - Array, FixedArray, Dictionary - this means that we can more easily add new functions to these types.

# Checklist

- [x] Remove all TODOs, debug prints, whitespace changes
- [x] Add `review wanted` label, remove "WIP" in PR title

### CODE REVIEW

**Comment by bearbin** [comment]
This needs a rebase and conflict resolution before final review and merging.

**Review by bearbin — CHANGES_REQUESTED** [review]

**Comment by SusanEisenbach** [comment]
Conflicting files
Sources/AST/Environment/Environment+Additions.swift
Sources/AST/Environment/Environment+Checks.swift
Sources/AST/Environment/Environment+MatchFunction.swift
Sources/AST/Environment/Environment+Type.swift
Sources/AST/Environment/Environment.swift
Sources/IRGen/Expression/IRAttemptExpression.swift
Sources/IRGen/Expression/IRSubscriptExpression.swift
Sources/IRGen/Function/IRStatement.swift
Sources/IRGen/IRContract.swift
Sources/IRGen/Preprocessor/IRPreprocessor.swift
Sources/IRGen/Runtime/IRFunctionSelector.swift
Sources/IRGen/Runtime/IRRuntimeFunction.swift
Sources/SemanticAnalyzer/SemanticAnalyzer+Components.swift
Sources/TypeChecker/TypeChecker+Expressions.swift
Sources/TypeChecker/TypeChecker+Statements.swift
Sources/flintc/StandardLibrary.swift
Tests/SemanticTests/operand_types.flint
Tests/SemanticTests/undeclared_type.flint

**Comment by DJRHails** [comment]
Just tidying up some old PRs

**Comment by bearbin** [comment]
Thought you'd pushed a new commit for a second!

**Pull request closed without merging**
