### PR TITLE
WIP: Enhanced FlintDAO

### PR DESCRIPTION
**Pull request by bearbin**
Builds on #411, but compiles and shows some additional features.

### CODE REVIEW

**Comment by bearbin** [comment]
We should really add some tests for these language properties, and check that my fixes to the compiler don't need to be extended to cover more edge cases.

**Comment by SusanEisenbach** [comment]
The group project is currently working on choosing (and starting to populate) a unit test framework because they have been caught out by bugs in the implementation. They say that the end to end testing framework does not catch everything.

On 1 Nov 2018, at 21:54, Alexander Harkness <notifications@github.com<mailto:notifications@github.com>> wrote:


We should really add some tests for these language properties, and check that my fixes to the compiler don't need to be extended to cover more edge cases.

**Comment by SusanEisenbach** [comment]
Why does the CI test fail? Can it be fixed?

**Comment by bearbin** [comment]
I'm not sure why it failed, it needs further investigation - it's nothing to do with the Flint code in the contract though.

**Comment by bearbin** [comment]
It doesn't fail on my machine, I've restarted the build - perhaps it is a random failure in the compiler.

**Comment by SusanEisenbach** [comment]
The CI test failed, but I took Alex's word that it is fine as I wished to make it visible.

**Pull request merged**
