### PR TITLE
Mangle function names. Fixes #124

### LINKED ISSUE #124: Fix conflicts between user-defined functions and IULIA built-in functions
E.g. A function called `add` cannot be defined.

### PR DESCRIPTION
**Pull request by bearbin**
Fixes #124

### CODE REVIEW

**Comment by franklinsch** [comment]
Could you briefly describe how the new mangling process works?

**Comment by bearbin** [comment]
The first change is to the MangleFunctionName function, where I adjust the mangling format to use `$` instead of `_` as user-defined identifiers can now use `_`.

The mangling process as a whole relies on the IULIAPreprocessor loading mangled names for functions into the `mangledIdentifier` property of `FunctionDeclarations` and `FunctionCalls`. This `mangledIdentifier` is then used rather than the `identifier.name` in outputting IULIA code for function calls and declarations. The selector and interface generation however uses the unmangled function name for the hash and comment, allowing external calls using the original function names.

**Comment by franklinsch** [comment]
Ah, that's awesome! Please resolve the conflicts and I'll merge.

**Comment by bearbin** [comment]
Merge?

**Pull request merged**
